//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Mvc.ItemProviderServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthorOutputDto", Namespace="http://schemas.datacontract.org/2004/07/Library.Business.Services.Provider.Dtos")]
    [System.SerializableAttribute()]
    public partial class AuthorOutputDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Library.Mvc.ItemProviderServices.AuthorDto[] AuthorDtosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Library.Mvc.ItemProviderServices.AuthorDto[] AuthorDtos {
            get {
                return this.AuthorDtosField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorDtosField, value) != true)) {
                    this.AuthorDtosField = value;
                    this.RaisePropertyChanged("AuthorDtos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthorDto", Namespace="http://schemas.datacontract.org/2004/07/Library.Business.Services.Provider.Dtos")]
    [System.SerializableAttribute()]
    public partial class AuthorDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PublisherOutputDto", Namespace="http://schemas.datacontract.org/2004/07/Library.Business.Services.Provider.Dtos")]
    [System.SerializableAttribute()]
    public partial class PublisherOutputDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Library.Mvc.ItemProviderServices.PublisherDto[] PublisherDtosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Library.Mvc.ItemProviderServices.PublisherDto[] PublisherDtos {
            get {
                return this.PublisherDtosField;
            }
            set {
                if ((object.ReferenceEquals(this.PublisherDtosField, value) != true)) {
                    this.PublisherDtosField = value;
                    this.RaisePropertyChanged("PublisherDtos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PublisherDto", Namespace="http://schemas.datacontract.org/2004/07/Library.Business.Services.Provider.Dtos")]
    [System.SerializableAttribute()]
    public partial class PublisherDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenreOutputDto", Namespace="http://schemas.datacontract.org/2004/07/Library.Business.Services.Provider.Dtos")]
    [System.SerializableAttribute()]
    public partial class GenreOutputDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Library.Mvc.ItemProviderServices.GenreDto[] GenreDtosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Library.Mvc.ItemProviderServices.GenreDto[] GenreDtos {
            get {
                return this.GenreDtosField;
            }
            set {
                if ((object.ReferenceEquals(this.GenreDtosField, value) != true)) {
                    this.GenreDtosField = value;
                    this.RaisePropertyChanged("GenreDtos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenreDto", Namespace="http://schemas.datacontract.org/2004/07/Library.Business.Services.Provider.Dtos")]
    [System.SerializableAttribute()]
    public partial class GenreDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SeriesOutputDto", Namespace="http://schemas.datacontract.org/2004/07/Library.Business.Services.Provider.Dtos")]
    [System.SerializableAttribute()]
    public partial class SeriesOutputDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Library.Mvc.ItemProviderServices.SeriesDto[] SeriesDtosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Library.Mvc.ItemProviderServices.SeriesDto[] SeriesDtos {
            get {
                return this.SeriesDtosField;
            }
            set {
                if ((object.ReferenceEquals(this.SeriesDtosField, value) != true)) {
                    this.SeriesDtosField = value;
                    this.RaisePropertyChanged("SeriesDtos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SeriesDto", Namespace="http://schemas.datacontract.org/2004/07/Library.Business.Services.Provider.Dtos")]
    [System.SerializableAttribute()]
    public partial class SeriesDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShelfOutputDto", Namespace="http://schemas.datacontract.org/2004/07/Library.Business.Services.Provider.Dtos")]
    [System.SerializableAttribute()]
    public partial class ShelfOutputDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Library.Mvc.ItemProviderServices.ShelfDto[] ShelfDtosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Library.Mvc.ItemProviderServices.ShelfDto[] ShelfDtos {
            get {
                return this.ShelfDtosField;
            }
            set {
                if ((object.ReferenceEquals(this.ShelfDtosField, value) != true)) {
                    this.ShelfDtosField = value;
                    this.RaisePropertyChanged("ShelfDtos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShelfDto", Namespace="http://schemas.datacontract.org/2004/07/Library.Business.Services.Provider.Dtos")]
    [System.SerializableAttribute()]
    public partial class ShelfDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RackOutputDto", Namespace="http://schemas.datacontract.org/2004/07/Library.Business.Services.Provider.Dtos")]
    [System.SerializableAttribute()]
    public partial class RackOutputDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Library.Mvc.ItemProviderServices.RackDto[] RackDtosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Library.Mvc.ItemProviderServices.RackDto[] RackDtos {
            get {
                return this.RackDtosField;
            }
            set {
                if ((object.ReferenceEquals(this.RackDtosField, value) != true)) {
                    this.RackDtosField = value;
                    this.RaisePropertyChanged("RackDtos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RackDto", Namespace="http://schemas.datacontract.org/2004/07/Library.Business.Services.Provider.Dtos")]
    [System.SerializableAttribute()]
    public partial class RackDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="com.sense.business.Services", ConfigurationName="ItemProviderServices.ItemProviderService")]
    public interface ItemProviderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="com.sense.business.Services/ItemProviderService/Authors", ReplyAction="com.sense.business.Services/ItemProviderService/AuthorsResponse")]
        Library.Mvc.ItemProviderServices.AuthorOutputDto Authors();
        
        [System.ServiceModel.OperationContractAttribute(Action="com.sense.business.Services/ItemProviderService/Authors", ReplyAction="com.sense.business.Services/ItemProviderService/AuthorsResponse")]
        System.Threading.Tasks.Task<Library.Mvc.ItemProviderServices.AuthorOutputDto> AuthorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="com.sense.business.Services/ItemProviderService/Publishers", ReplyAction="com.sense.business.Services/ItemProviderService/PublishersResponse")]
        Library.Mvc.ItemProviderServices.PublisherOutputDto Publishers();
        
        [System.ServiceModel.OperationContractAttribute(Action="com.sense.business.Services/ItemProviderService/Publishers", ReplyAction="com.sense.business.Services/ItemProviderService/PublishersResponse")]
        System.Threading.Tasks.Task<Library.Mvc.ItemProviderServices.PublisherOutputDto> PublishersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="com.sense.business.Services/ItemProviderService/Genres", ReplyAction="com.sense.business.Services/ItemProviderService/GenresResponse")]
        Library.Mvc.ItemProviderServices.GenreOutputDto Genres();
        
        [System.ServiceModel.OperationContractAttribute(Action="com.sense.business.Services/ItemProviderService/Genres", ReplyAction="com.sense.business.Services/ItemProviderService/GenresResponse")]
        System.Threading.Tasks.Task<Library.Mvc.ItemProviderServices.GenreOutputDto> GenresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="com.sense.business.Services/ItemProviderService/Series", ReplyAction="com.sense.business.Services/ItemProviderService/SeriesResponse")]
        Library.Mvc.ItemProviderServices.SeriesOutputDto Series();
        
        [System.ServiceModel.OperationContractAttribute(Action="com.sense.business.Services/ItemProviderService/Series", ReplyAction="com.sense.business.Services/ItemProviderService/SeriesResponse")]
        System.Threading.Tasks.Task<Library.Mvc.ItemProviderServices.SeriesOutputDto> SeriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="com.sense.business.Services/ItemProviderService/Shelfs", ReplyAction="com.sense.business.Services/ItemProviderService/ShelfsResponse")]
        Library.Mvc.ItemProviderServices.ShelfOutputDto Shelfs();
        
        [System.ServiceModel.OperationContractAttribute(Action="com.sense.business.Services/ItemProviderService/Shelfs", ReplyAction="com.sense.business.Services/ItemProviderService/ShelfsResponse")]
        System.Threading.Tasks.Task<Library.Mvc.ItemProviderServices.ShelfOutputDto> ShelfsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="com.sense.business.Services/ItemProviderService/Racks", ReplyAction="com.sense.business.Services/ItemProviderService/RacksResponse")]
        Library.Mvc.ItemProviderServices.RackOutputDto Racks();
        
        [System.ServiceModel.OperationContractAttribute(Action="com.sense.business.Services/ItemProviderService/Racks", ReplyAction="com.sense.business.Services/ItemProviderService/RacksResponse")]
        System.Threading.Tasks.Task<Library.Mvc.ItemProviderServices.RackOutputDto> RacksAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ItemProviderServiceChannel : Library.Mvc.ItemProviderServices.ItemProviderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ItemProviderServiceClient : System.ServiceModel.ClientBase<Library.Mvc.ItemProviderServices.ItemProviderService>, Library.Mvc.ItemProviderServices.ItemProviderService {
        
        public ItemProviderServiceClient() {
        }
        
        public ItemProviderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ItemProviderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ItemProviderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ItemProviderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Library.Mvc.ItemProviderServices.AuthorOutputDto Authors() {
            return base.Channel.Authors();
        }
        
        public System.Threading.Tasks.Task<Library.Mvc.ItemProviderServices.AuthorOutputDto> AuthorsAsync() {
            return base.Channel.AuthorsAsync();
        }
        
        public Library.Mvc.ItemProviderServices.PublisherOutputDto Publishers() {
            return base.Channel.Publishers();
        }
        
        public System.Threading.Tasks.Task<Library.Mvc.ItemProviderServices.PublisherOutputDto> PublishersAsync() {
            return base.Channel.PublishersAsync();
        }
        
        public Library.Mvc.ItemProviderServices.GenreOutputDto Genres() {
            return base.Channel.Genres();
        }
        
        public System.Threading.Tasks.Task<Library.Mvc.ItemProviderServices.GenreOutputDto> GenresAsync() {
            return base.Channel.GenresAsync();
        }
        
        public Library.Mvc.ItemProviderServices.SeriesOutputDto Series() {
            return base.Channel.Series();
        }
        
        public System.Threading.Tasks.Task<Library.Mvc.ItemProviderServices.SeriesOutputDto> SeriesAsync() {
            return base.Channel.SeriesAsync();
        }
        
        public Library.Mvc.ItemProviderServices.ShelfOutputDto Shelfs() {
            return base.Channel.Shelfs();
        }
        
        public System.Threading.Tasks.Task<Library.Mvc.ItemProviderServices.ShelfOutputDto> ShelfsAsync() {
            return base.Channel.ShelfsAsync();
        }
        
        public Library.Mvc.ItemProviderServices.RackOutputDto Racks() {
            return base.Channel.Racks();
        }
        
        public System.Threading.Tasks.Task<Library.Mvc.ItemProviderServices.RackOutputDto> RacksAsync() {
            return base.Channel.RacksAsync();
        }
    }
}
