//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Mvc.BookServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookOutputDto", Namespace="http://schemas.datacontract.org/2004/07/Library.Business.Dtos")]
    [System.SerializableAttribute()]
    public partial class BookOutputDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Library.Mvc.BookServices.BookDto[] BooksField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Library.Mvc.BookServices.BookDto[] Books {
            get {
                return this.BooksField;
            }
            set {
                if ((object.ReferenceEquals(this.BooksField, value) != true)) {
                    this.BooksField = value;
                    this.RaisePropertyChanged("Books");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookDto", Namespace="http://schemas.datacontract.org/2004/07/Library.Business.Dtos")]
    [System.SerializableAttribute()]
    public partial class BookDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PublishDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublisherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShelfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SkinTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Genre {
            get {
                return this.GenreField;
            }
            set {
                if ((object.ReferenceEquals(this.GenreField, value) != true)) {
                    this.GenreField = value;
                    this.RaisePropertyChanged("Genre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string No {
            get {
                return this.NoField;
            }
            set {
                if ((object.ReferenceEquals(this.NoField, value) != true)) {
                    this.NoField = value;
                    this.RaisePropertyChanged("No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PublishDate {
            get {
                return this.PublishDateField;
            }
            set {
                if ((this.PublishDateField.Equals(value) != true)) {
                    this.PublishDateField = value;
                    this.RaisePropertyChanged("PublishDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Publisher {
            get {
                return this.PublisherField;
            }
            set {
                if ((object.ReferenceEquals(this.PublisherField, value) != true)) {
                    this.PublisherField = value;
                    this.RaisePropertyChanged("Publisher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rack {
            get {
                return this.RackField;
            }
            set {
                if ((this.RackField.Equals(value) != true)) {
                    this.RackField = value;
                    this.RaisePropertyChanged("Rack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Serie {
            get {
                return this.SerieField;
            }
            set {
                if ((object.ReferenceEquals(this.SerieField, value) != true)) {
                    this.SerieField = value;
                    this.RaisePropertyChanged("Serie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Shelf {
            get {
                return this.ShelfField;
            }
            set {
                if ((object.ReferenceEquals(this.ShelfField, value) != true)) {
                    this.ShelfField = value;
                    this.RaisePropertyChanged("Shelf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SkinType {
            get {
                return this.SkinTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SkinTypeField, value) != true)) {
                    this.SkinTypeField = value;
                    this.RaisePropertyChanged("SkinType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookInputDto", Namespace="http://schemas.datacontract.org/2004/07/Library.Business.Dtos")]
    [System.SerializableAttribute()]
    public partial class BookInputDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GenreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PublishDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PublisherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SerieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShelfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SkinTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((this.AuthorField.Equals(value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Genre {
            get {
                return this.GenreField;
            }
            set {
                if ((this.GenreField.Equals(value) != true)) {
                    this.GenreField = value;
                    this.RaisePropertyChanged("Genre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string No {
            get {
                return this.NoField;
            }
            set {
                if ((object.ReferenceEquals(this.NoField, value) != true)) {
                    this.NoField = value;
                    this.RaisePropertyChanged("No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PublishDate {
            get {
                return this.PublishDateField;
            }
            set {
                if ((this.PublishDateField.Equals(value) != true)) {
                    this.PublishDateField = value;
                    this.RaisePropertyChanged("PublishDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Publisher {
            get {
                return this.PublisherField;
            }
            set {
                if ((this.PublisherField.Equals(value) != true)) {
                    this.PublisherField = value;
                    this.RaisePropertyChanged("Publisher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rack {
            get {
                return this.RackField;
            }
            set {
                if ((this.RackField.Equals(value) != true)) {
                    this.RackField = value;
                    this.RaisePropertyChanged("Rack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Serie {
            get {
                return this.SerieField;
            }
            set {
                if ((this.SerieField.Equals(value) != true)) {
                    this.SerieField = value;
                    this.RaisePropertyChanged("Serie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Shelf {
            get {
                return this.ShelfField;
            }
            set {
                if ((this.ShelfField.Equals(value) != true)) {
                    this.ShelfField = value;
                    this.RaisePropertyChanged("Shelf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SkinType {
            get {
                return this.SkinTypeField;
            }
            set {
                if ((this.SkinTypeField.Equals(value) != true)) {
                    this.SkinTypeField = value;
                    this.RaisePropertyChanged("SkinType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="com.sense.services.Services", ConfigurationName="BookServices.BookService")]
    public interface BookService {
        
        [System.ServiceModel.OperationContractAttribute(Action="com.sense.services.Services/BookService/GetBookList", ReplyAction="com.sense.services.Services/BookService/GetBookListResponse")]
        Library.Mvc.BookServices.BookOutputDto GetBookList();
        
        [System.ServiceModel.OperationContractAttribute(Action="com.sense.services.Services/BookService/GetBookList", ReplyAction="com.sense.services.Services/BookService/GetBookListResponse")]
        System.Threading.Tasks.Task<Library.Mvc.BookServices.BookOutputDto> GetBookListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="com.sense.services.Services/BookService/AddBook", ReplyAction="com.sense.services.Services/BookService/AddBookResponse")]
        bool AddBook(Library.Mvc.BookServices.BookInputDto input);
        
        [System.ServiceModel.OperationContractAttribute(Action="com.sense.services.Services/BookService/AddBook", ReplyAction="com.sense.services.Services/BookService/AddBookResponse")]
        System.Threading.Tasks.Task<bool> AddBookAsync(Library.Mvc.BookServices.BookInputDto input);
        
        [System.ServiceModel.OperationContractAttribute(Action="com.sense.services.Services/BookService/UpdateBook", ReplyAction="com.sense.services.Services/BookService/UpdateBookResponse")]
        bool UpdateBook(Library.Mvc.BookServices.BookDto input);
        
        [System.ServiceModel.OperationContractAttribute(Action="com.sense.services.Services/BookService/UpdateBook", ReplyAction="com.sense.services.Services/BookService/UpdateBookResponse")]
        System.Threading.Tasks.Task<bool> UpdateBookAsync(Library.Mvc.BookServices.BookDto input);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BookServiceChannel : Library.Mvc.BookServices.BookService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookServiceClient : System.ServiceModel.ClientBase<Library.Mvc.BookServices.BookService>, Library.Mvc.BookServices.BookService {
        
        public BookServiceClient() {
        }
        
        public BookServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Library.Mvc.BookServices.BookOutputDto GetBookList() {
            return base.Channel.GetBookList();
        }
        
        public System.Threading.Tasks.Task<Library.Mvc.BookServices.BookOutputDto> GetBookListAsync() {
            return base.Channel.GetBookListAsync();
        }
        
        public bool AddBook(Library.Mvc.BookServices.BookInputDto input) {
            return base.Channel.AddBook(input);
        }
        
        public System.Threading.Tasks.Task<bool> AddBookAsync(Library.Mvc.BookServices.BookInputDto input) {
            return base.Channel.AddBookAsync(input);
        }
        
        public bool UpdateBook(Library.Mvc.BookServices.BookDto input) {
            return base.Channel.UpdateBook(input);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateBookAsync(Library.Mvc.BookServices.BookDto input) {
            return base.Channel.UpdateBookAsync(input);
        }
    }
}
